{% set name = "torch-tb-profiler" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/torch_tb_profiler-{{ version }}.tar.gz
  sha256: 8b8d29b2de960b3c4423087b23cec29beaf9ac3a8c7b046c18fd25b218f726b1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - pandas >=1.0.0
    - python >={{ python_min }}
    - tensorboard >=1.15,!=2.1.0

test:
  imports:
    - torch_tb_profiler
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pytorch/kineto/tree/main/tb_plugin
  summary: 'Tensoboard Plugin that provides visualization of PyTorch profiling'
  dev_url: https://github.com/pytorch/kineto/tree/main/tb_plugin
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jeongseok-meta
